# Generated by Django 5.1.2 on 2024-10-28 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rimtex', '0002_delete_millshift'),
    ]

    operations = [
        migrations.CreateModel(
            name='MillShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_number', models.CharField(max_length=10)),
                ('shift_name', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('mill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rimtex.mill')),
            ],
        ),
    ]
