# Generated by Django 5.1.2 on 2024-10-29 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rimtex', '0003_millshift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='millline',
            name='layout_data',
            field=models.JSONField(default=dict),
        ),
    ]
