# Generated by Django 5.1.2 on 2024-11-04 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rimtex', '0006_alter_machinesetting_input_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinesetting',
            name='input_time',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='machinesetting',
            name='input_tolerance',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='machinesetting',
            name='output_time',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='machinesetting',
            name='output_tolerance',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
