# Generated by Django 5.1.2 on 2024-11-04 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rimtex', '0008_alter_machinesetting_input_time_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MachineSetting',
        ),
    ]
