# Generated by Django 5.1.2 on 2024-11-09 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rimtex', '0010_machinesetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mill_id', models.IntegerField()),
                ('line_id', models.IntegerField()),
                ('device_type', models.CharField(max_length=50)),
                ('count', models.IntegerField(default=0)),
            ],
            options={
                'unique_together': {('mill_id', 'line_id', 'device_type')},
            },
        ),
    ]
