# Generated by Django 5.1.2 on 2024-11-17 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rimtex', '0011_machineoverride'),
    ]

    operations = [
        migrations.AddField(
            model_name='millmachine',
            name='is_red_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='millmachine',
            name='red_flag_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='millmachine',
            name='red_flag_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
