# Generated by Django 5.1.2 on 2024-11-18 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rimtex', '0015_machineconnectionlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MachineConnectionLog',
        ),
    ]
