# Generated by Django 5.1.2 on 2024-11-18 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rimtex', '0016_delete_machineconnectionlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineConnectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_id', models.IntegerField()),
                ('mill_id', models.IntegerField()),
                ('can_id', models.CharField(max_length=255)),
                ('output_machine', models.CharField(max_length=255)),
                ('output_time', models.DateTimeField(blank=True, null=True)),
                ('input_machine', models.CharField(blank=True, max_length=255, null=True)),
                ('input_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
