# Generated by Django 5.1.2 on 2024-11-19 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rimtex', '0017_machineconnectionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='machineconnectionlog',
            name='input_position',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='machineconnectionlog',
            name='output_position',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
