# Generated by Django 5.1.2 on 2024-12-16 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rimtex', '0020_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='millshift',
            name='shift_number',
        ),
    ]
